apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: rishi236/hello:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000


---
apiVersion: v1
kind: Service
  
metadata:
  name: hello
spec:
  type: LoadBalancer
  selector:
    app: hello
  ports:
  - port: 5000
    targetPort: 5000
