- name: Pull artifacts from nexus
  become: true
  get_url:
     url: http://43.204.111.29:8081/repository/nex_repo/com/example/demo/0.0.1-SNAPSHOT/maven-metadata.xml.sha1
     dest: /opt/tomcat/apache-tomcat-10.0.8/webapps
